[WIP] - Testing smoke tests

diff --git a/.github/workflows/edge-smoke-test.yml b/.github/workflows/edge-smoke-test.yml
--- a/.github/workflows/edge-smoke-test.yml
+++ b/.github/workflows/edge-smoke-test.yml
@@ -48,6 +48,7 @@ jobs:
           kubectl get pods -n test >> ${{ runner.temp }}/logs/edge-pod.log
           echo "=== LOGS ===" >> ${{ runner.temp }}/logs/edge-pod.log
           kubectl logs -l app.kubernetes.io/instance=$RELEASE_NAME --tail -1 -n test >> ${{ runner.temp }}/logs/edge-pod.log 2>&1 || echo "Failed to retrieve pod logs" >> ${{ runner.temp }}/logs/edge-pod.log
+          kubectl logs -n test pods/hivemq-test-connection-smoke-test-release >> ${{ runner.temp }}/logs/test-pod.log 2>&1 || echo "Failed to retrieve test pod logs" >> ${{ runner.temp }}/logs/test-pod.log
 
       - name: Upload HiveMQ Edge Pod logs
         if: always()
@@ -61,6 +62,11 @@ jobs:
         if: always()
         run: |
           cat ${{ runner.temp }}/logs/edge-pod.log
+
+      - name: Print Test Pod logs
+        if: always()
+        run: |
+          cat ${{ runner.temp }}/logs/test-pod.log
 
       - name: Uninstall HiveMQ Edge chart
         if: always()
